### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by chengwei710** [anchengjian/vue-nw-seed#8]
192:vue-nw-seed conway$ npm run dev

> vue-nw-seed@0.1.0 dev /Users/conway/Repository/GitHub/vue-nw-seed
> node build/dev-server.js

/Users/conway/Repository/GitHub/vue-nw-seed/config/index.js:5
  return path.resolve.apply(path, [__dirname, '..'].concat(...arguments))
                                                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/conway/Repository/GitHub/vue-nw-seed/build/dev-server.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by anchengjian** [comment]
```
function resolve() {
  return path.resolve.apply(path, [__dirname, '..'].concat(...arguments))
}
```

这里用到了ES2015的 `...` 扩展运算符，可以升级 node 版本就解决了

**Comment by anchengjian** [comment]
下次试着兼容下低版本的 node

**Comment by chengwei710** [comment]
7.10也不工作, 6.10工作正常

**Comment by zhangdp** [comment]
请问最终是怎么解决的呢？我电脑安装的是v8.15.0还是不行
